# Basic information
baseURL = 'https://danicavu.github.io/website' # Should be updated to your domain
languageCode = 'en-us'
theme="archie"

# Metadata to edit
title = 'Danica Vu'
copyright = "© Danica Vu"
blogTitle='Check out my blog:'

# For code highlighting
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Social media for footer icons, could add more

[[params.social]]
name = "Linkedin"
icon = "linkedin"
url = "https://www.linkedin.com/in/danicavu/"

# Menu items
[[menu.main]]
name = "Home"
url = "/"
weight = 1 # lower number sorts them to the left

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2

